In [3]:
#Implement a python program to demonstrate the following using numpy
#Array manipulation, sorting, searching, and splitting

import numpy as np 
lt = []
size = int(input('Enter size: '))
for i in range(0,size):
    ele = int(input())
    lt.append(ele)

print("Current List: ",lt)

print("Array manipulation, sorting, searching, and splitting using numpy")
#Array manipulation
arr = np.array(lt)
print("Numpy Array: ",arr)

#Array sorting
arr = np.sort(arr)
print("Numpy Array after sorting: ",arr)

#Searching in array
ele = int(input('Enter element to search'))
index_ = np.where(arr == ele)
print('Element ',ele,' found at position: ',index_)

#Splitting the array
splitting_value = int(input('Enter value to split: '))
new_arr = np.split(arr,splitting_value)
print('Array after splitting: ',new_arr)

Current List:  [3, 2, 1, 1, 2, 4]
Array manipulation, sorting, searching, and splitting using numpy
Numpy Array:  [3 2 1 1 2 4]
Numpy Array after sorting:  [1 1 2 2 3 4]
Element  3  found at position:  (array([4], dtype=int64),)
Array after splitting:  [array([1, 1, 2]), array([2, 3, 4])]


In [5]:
#Implement a python program to demonstrate the following using numpy
#Broadcasting and plotting numpy array

from numpy import array,argmin,sqrt,sum

observation = array([111.0,188.0])
codes = array([[102.0,208.0],[132.0,193.0],[95.0,155.0],[57.0,173.0]])

diff = codes - observation
dist = sqrt(sum(diff ** 2,axis=-1))

print(observation,observation.shape)
print(codes,codes.shape)
print(diff,diff.shape)
print(dist,dist.shape)
argmin(dist)



[111. 188.] (2,)
[[102. 208.]
 [132. 193.]
 [ 95. 155.]
 [ 57. 173.]] (4, 2)
[[ -9.  20.]
 [ 21.   5.]
 [-16. -33.]
 [-54. -15.]] (4, 2)
[21.9317122  21.58703314 36.67424164 56.04462508] (4,)


1