In [9]:
#Broadcasting and plotting numpy array

from numpy import array,argmin,sqrt,sum,argmax

observation = array([111.0,188.0])
codes = array([[102.0,203.0],[132.0,193.0],[45.0,155.0],[57.0,173.0]])

diff = codes - observation
dist = sqrt(sum(diff ** 2,axis=-1))

print(observation,observation.shape)
print(codes,codes.shape)
print(diff,diff.shape)
print(dist,dist.shape)
argmin(dist)
argmax(dist)

[111. 188.] (2,)
[[102. 203.]
 [132. 193.]
 [ 45. 155.]
 [ 57. 173.]] (4, 2)
[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]] (4, 2)
[17.49285568 21.58703314 73.79024326 56.04462508] (4,)


2

In [14]:
#Implement a python program to demonstrate the following using numpy
#Array manipulation, sorting, searching, and splitting

import numpy as np 
lt = []
size = int(input('Enter size: '))
for i in range(0,size):
    ele = int(input())
    lt.append(ele)

print("Current List: ",lt)

print("Array manipulation, sorting, searching, and splitting using numpy")
#Array manipulation
arr = np.array(lt)
print("Numpy Array: ",arr)

#Array sorting
arr = np.sort(arr)
print("Numpy Array after sorting: ",arr)

#Searching in array
ele = int(input('Enter element to search: '))
index_ = np.where(arr == ele)
print('Element ',ele,' found at position: ',index_)

#Splitting the array
splitting_value = int(input('Enter value to split: '))
new_arr = np.array_split(arr,splitting_value)
print('Array after splitting: ',new_arr)

Enter size: 5
3
2
1
4
7
Current List:  [3, 2, 1, 4, 7]
Array manipulation, sorting, searching, and splitting using numpy
Numpy Array:  [3 2 1 4 7]
Numpy Array after sorting:  [1 2 3 4 7]
Enter element to search: 8
Element  8  found at position:  (array([], dtype=int64),)
Enter value to split: 8
Array after splitting:  [array([1]), array([2]), array([3]), array([4]), array([7]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
