In [15]:
#Array manipulation,searching, sorting and splitting
import numpy as np
lt = []
n = int(input("Enter the number of elements : "))
for i in range(0,n):
    ele = int(input())
    lt.append(ele)
print(lt)
arr = np.array(lt)
arr = np.sort(lt)
print("Sorted Array = {}".format(arr))
ele = int(input("Enter element to search : "))
indx = np.where(arr == ele)
print("Index = {}".format(indx))
s = int(input("Enter splitting value : "))
newarr = np.array_split(arr,s)
print(newarr)

Enter the number of elements : 5
2
3
4
5
6
[2, 3, 4, 5, 6]
Sorted Array = [2 3 4 5 6]
Enter element to search : 4
Index = (array([2]),)


KeyboardInterrupt: Interrupted by user

In [14]:
#Broadcasting and plotting Numpy arrays
import numpy as np
from numpy import array, argmin, argmax, sqrt, sum
observation = array([111.0,188.0])
codes = array([[102.0,203.0],[132.0,193.0],[45.0,155.0],[57.0,173.0]])

diff = codes - observation #broadcast happens here
dist = sqrt(sum(diff **2, axis = -1))

print(observation,observation.shape)
print(codes,codes.shape)
print(diff,diff.shape)
print(dist,dist.shape)
print(argmin(dist))
argmax(dist)

[111. 188.] (2,)
[[102. 203.]
 [132. 193.]
 [ 45. 155.]
 [ 57. 173.]] (4, 2)
[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]] (4, 2)
[17.49285568 21.58703314 73.79024326 56.04462508] (4,)
0


2